import type { Metadata } from "next";
import { ArrowRight, Check } from "lucide-react";
import { BookingButton } from "@/components/site-shell";
import { Breadcrumbs, CTASection, PageHero, SectionHeading } from "@/components/shared";
import { services } from "@/data/content";

export const metadata: Metadata = { title: "Interior Design Services Nepal", description: "Explore on-site interior consultation, space planning, furniture placement, color, lighting, material and home styling services in Nepal." };
const details: Record<string,string[]> = { "interior-consultation": ["Personal design direction", "Priorities and budget alignment", "Coordinated next-step plan"], "on-site-consultation": ["Completed-property visit", "Floor-plan and measurement review", "Light, scale and circulation assessment"], "space-planning": ["Room zoning and layout", "Comfortable circulation", "Practical use of available space"], "furniture-placement": ["Size and proportion guidance", "Arrangement recommendations", "Existing furniture integration"], "color-consultation": ["Wall and accent colors", "Fabric and furniture coordination", "A balanced whole-home palette"], "lighting-guidance": ["Ambient and task lighting", "Decorative fixture direction", "Warmth and visual comfort"], "materials-finishes": ["Wood tone coordination", "Textile and texture pairing", "Surface and finish guidance"], "decor-styling": ["Art, mirrors and rugs", "Curtains, cushions and accessories", "Final-layer room styling"] };
export default function ServicesPage(){ return <main id="main-content"><PageHero eyebrow="Our services" title="Guidance that brings every interior choice into focus." text="Choose support for one room or a complete home. Every service is tailored to your space, taste and practical needs."/><Breadcrumbs current="Services" />
  <section className="section services-intro"><SectionHeading eyebrow="Consultation, not construction" title="We help you shape the experience of your completed home." intro="Our work focuses on planning, furnishing, color, lighting, materials, styling and product selection. It does not include structural alterations." /><div className="service-types"><div><strong>Room-specific design</strong><p>Focused advice for a living room, bedroom, dining area, guest room, home office or another space.</p></div><div><strong>Whole-home consultation</strong><p>A consistent interior direction across the home, from major furniture decisions to the final decorative layer.</p></div></div></section>
  <section className="service-details section">{services.map(({slug,title,summary,icon:Icon},i)=><article id={slug} key={slug} className="service-detail"><div className="service-number">{String(i+1).padStart(2,"0")}</div><div className="service-icon"><Icon /></div><div><h2>{title}</h2><p>{summary}</p><ul>{details[slug].map(x=><li key={x}><Check size={15}/>{x}</li>)}</ul></div><BookingButton>Book this consultation <ArrowRight size={16}/></BookingButton></article>)}</section><CTASection /></main> }
