import type { Metadata } from "next";
import Image from "next/image";
import { Eye, HeartHandshake, Scale, ShieldCheck, Sparkles, Target } from "lucide-react";
import { Breadcrumbs, CTASection, PageHero, SectionHeading } from "@/components/shared";

export const metadata: Metadata = { title: "About Our Interior Design Approach", description: "Learn how our Nepal interior design consultation studio helps homeowners move from a completed house to a beautiful, functional and personal home." };

export default function AboutPage() { return <main id="main-content"><PageHero eyebrow="About the studio" title="Designing homes around the people who live in them." text="We help homeowners turn a finished structure into a deeply personal place—without changing the building itself." image="/images/editorial-bedroom.png" /><Breadcrumbs current="About" />
  <section className="section story-grid"><div><SectionHeading eyebrow="Our story" title="The space between a finished house and a finished home." /><p className="lead">Once construction ends, hundreds of interior decisions begin. That is where we come in.</p><p>Our studio was created to help homeowners make those decisions with confidence. We bring together room planning, color, furniture, lighting, finishes and styling so each choice supports a clear whole.</p><p>Rather than applying one signature look, we begin with your home and your life: the architecture already in place, the people who will use it and the atmosphere you want to create.</p></div><div className="story-image"><Image src="/images/hero-living-room.png" alt="Considered living room concept" width={1536} height={1024} sizes="(max-width: 780px) 100vw, 50vw" /><span>Completed architecture. Considered interiors.</span></div></section>
  <section className="mission-band"><div className="section"><span className="eyebrow">Our mission</span><h2>To help homeowners create interiors that are</h2><div>{["Beautiful", "Functional", "Comfortable", "Personal", "Timeless"].map(x => <span key={x}>{x}</span>)}</div></div></section>
  <section className="section approach"><SectionHeading eyebrow="Our approach" title="No two homes—and no two families—are the same." intro="Every recommendation is shaped by what is real, useful and meaningful in your home." /><div className="approach-grid">{["House layout", "Room size", "Existing architecture", "Natural lighting", "Family lifestyle", "Personal taste", "Existing furniture", "Working budget", "Future needs"].map((x, i) => <div key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</div>)}</div></section>
  <section className="section scope-clarification"><div><span className="eyebrow">Our area of expertise</span><h2>We refine what is within the walls—not the walls themselves.</h2></div><div><p>We specialize in interior design consulting, styling, space planning and product recommendations. We do not alter structural elements of your property such as foundations, columns, beams or major building infrastructure.</p><p>This focus lets us give close attention to how your completed home feels, functions and reflects you.</p></div></section>
  <section className="section values"><SectionHeading eyebrow="What guides us" title="Values behind every recommendation." /><div className="value-grid">{[[Sparkles,"Thoughtful design"],[HeartHandshake,"Client first"],[Eye,"Attention to detail"],[Scale,"Practical beauty"],[ShieldCheck,"Quality"],[Target,"Transparency"]].map(([Icon, title]) => { const I=Icon as typeof Sparkles; return <div key={String(title)}><I /><h3>{String(title)}</h3><p>Considered choices, communicated clearly and designed for real life.</p></div>; })}</div></section>
  <section className="team-placeholder section-dark"><div className="section"><SectionHeading light eyebrow="The team" title="Introduce the people behind the studio." intro="These are intentional placeholders for verified team information and portraits." /><div className="team-grid">{["Founder / Creative Director", "Interior Designer", "Design Consultant"].map((role, i) => <article key={role}><div className="portrait-placeholder"><span>Portrait<br/>placeholder</span></div><h3>[TEAM MEMBER {i+1}]</h3><p>{role}</p></article>)}</div></div></section><CTASection /></main> }
